### ISSUE TITLE
testserver

### ISSUE THREAD

**Issue by vpereira** [innovationfactory/ruby-net-ldap#4]
i did try to connect to the test server, but i receive always the error. As client i'm using the file testldap.rb 

/x/.rvm/gems/ruby-1.9.2-p180@webgui2/gems/net-ldap-0.2.2/lib/net/ber/ber_parser.rb:84:in `parse_ber_object': Unsupported object type: id=96 (Net::BER::BerError)
        from /x.rvm/gems/ruby-1.9.2-p180@webgui2/gems/net-ldap-0.2.2/lib/net/ber/ber_parser.rb:166:in`read_ber'
        from /x/.rvm/gems/ruby-1.9.2-p180@webgui2/gems/net-ldap-0.2.2/lib/net/ber/ber_parser.rb:73:in `parse_ber_object'
        from /x/.rvm/gems/ruby-1.9.2-p180@webgui2/gems/net-ldap-0.2.2/lib/net/ber/ber_parser.rb:166:in`read_ber'
        from ldapserver.rb:24:in `read_ber!'
        from ldapserver.rb:68:in`receive_data'
        from /x/.rvm/gems/ruby-1.9.2-p180@webgui2/gems/eventmachine-1.0.0.beta.3/lib/eventmachine.rb:199:in `run_machine'
        from /x.rvm/gems/ruby-1.9.2-p180@webgui2/gems/eventmachine-1.0.0.beta.3/lib/eventmachine.rb:199:in`run'
        from ldapserver.rb:225:in `<main>'
x:testldapserver vpereira$

**Comment by innovationfactory** [comment]
We're really sorry, but we don't support ruby-net-ldap anymore. It was written by someone who left the company quite some time ago.

**Comment by nowhereman** [comment]
Go to https://github.com/ruby-ldap/ruby-net-ldap, it's now the offcial repository of ruby-net-ldap library.

**Comment by vpereira** [comment]
thanks!
